#####################################################################
# Configuration Spring de base
#####################################################################
# app name
spring:
  application:
    name:                            authentification-service
#jackson null default desactivate
  jackson:
    default-property-inclusion:      NON_NULL
#profiles spring
  profiles:
    active:                          maison

#####################################################################
# Security
#####################################################################
  ldap:
    embedded:
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:ldap-server.ldif
      base-dn: dc=globaz.tmmas,dc=ch
      port: 8389
      validation:
        enabled: false

# mode jar, port et context
server:
  port:                              ${PORT:8010}
  servlet.context-path:                       /authentification-service

#####################################################################
# Configuration Spring actuator
#####################################################################
management:
  server.servlet.context-path:                         /actuator

# configuration des endpoints
management:
  endpoint:
    hypermedia:
      enabled:                            true
    actuator:
      enabled:                            true
    beans:
      enabled:                            true
    env:
      enabled:                            true
    metrics:
      enabled:                            true
    health:
      enabled:                            true
    mappings:
      enabled:                            true
    docs:
      enabled:                            true
    logfile:
      enabled:                            true

