####### H2
#################### DataSource Configuration ##########################
#jdbc:
#  driverClassName: org.h2.Driver
#  url: jdbc:h2:mem:registration_02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#  user: sa
#  pass: sa
#init-db: false

#################### Hibernate Configuration ##########################
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl.auto: create-drop

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:registration_02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    pass: sa

########## Config jwt
lab.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: sebooom.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus